app/models/category.py
from app import db
from datetime import datetime

class Category(db.Model):
    __tablename__ = 'categories'

    id         = db.Column(db.Integer, primary_key=True)
    name       = db.Column(db.String(100), nullable=False, unique=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f'<Category id={self.id}, name={self.name}>'


# Tabla intermedia para la relación muchos a muchos
class ProductCategory(db.Model):
    __tablename__ = 'product_categories'

    product_id = db.Column(db.Integer, db.ForeignKey('products.id', ondelete='CASCADE'), primary_key=True)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id', ondelete='CASCADE'), primary_key=True)

app/blueprints/category.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models import Category
from app import db

category = Blueprint('category', __name__)

#Ver lista de Categorías
@category.route('/categories', methods=['GET'])
def show():
    # Número de categorías por página
    per_page = 10

    # Obtener el número de página desde la URL (por defecto será 1 si no se proporciona)
    page = request.args.get('page', 1, type=int)

    # Obtener el término de búsqueda desde la URL (si lo hay)
    search = request.args.get('search', '', type=str)

    # Consultar y filtrar categorías por nombre (si se proporciona un término de búsqueda)
    query = Category.query.order_by(Category.name.asc())

    if search:
        query = query.filter(Category.name.ilike(f'%{search}%'))  # Filtrado por nombre, insensible a mayúsculas

    # Realizar la paginación
    categories = query.paginate(page=page, per_page=per_page, error_out=False)

    return render_template('category/show.html', categories=categories, search=search)





#Crear una nueva Categoría
@category.route('/categories/new', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        name = request.form['name']

        # Verificar si el nombre de la marca ya existe
        item_exists = Category.query.filter_by(name=name).first()
        if item_exists:
            flash('Ya existe un elemento con ese nombre. Por favor, elige otro.', 'danger')
            return redirect(url_for('category.create'))


        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Categoría agregada exitosamente', 'success')
        return redirect(url_for('category.show'))
    
    return render_template('category/create.html')


#Editar Categoría
@category.route('/categories/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    category = Category.query.get_or_404(id)

    if request.method == 'POST':
        name = request.form['name']

        # Verificar si el nombre de la categoría ya existe y no es la misma categoría que estamos editando
        item_exists = Category.query.filter_by(name=name).first()
        if item_exists and item_exists.id != category.id:
            flash('Ya existe un elemento con ese nombre. Por favor, elige otro.', 'danger')
            return redirect(url_for('category.edit', id=category.id))

        # Actualizar el nombre de la categoría
        category.name = name
        db.session.commit()
        flash('Categoría actualizada exitosamente', 'success')
        return redirect(url_for('category.show'))

    return render_template('category/edit.html', category=category)


#Eliminar Categoría
@category.route('/categories/delete/<int:id>', methods=['POST'])
def delete(id):
    category = Category.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()
    flash('Categoría eliminada exitosamente', 'success')
    return redirect(url_for('category.show'))

app/templates/category/create.html
{% extends "admin/layout.html" %}

{% block title %}Nueva Categoría{% endblock %}
{% block title_h1 %}Agregar Nueva Categoría{% endblock %}

{% block content %}
<div class="container mx-auto p-6">
    <div class="max-w-lg mx-auto bg-white p-8 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold text-center text-gray-700 mb-6">Agregar Nueva Categoría</h2>
        
        <form method="POST">
            <div class="mb-4">
                <label for="name" class="block text-lg font-medium text-gray-600">Nombre de la categoría</label>
                <input type="text" id="name" name="name" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" autocomplete="off" required>
            </div>

            <div class="flex justify-between">
                <button type="submit" class="px-6 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:ring-2 focus:ring-green-400">Agregar Categoría</button>
                <a href="{{ url_for('category.show') }}" class="px-6 py-2 bg-gray-300 text-gray-800 rounded-md hover:bg-gray-400 focus:ring-2 focus:ring-gray-400">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/category/edit.html
{% extends "admin/layout.html" %}

{% block title %}Editar Categoría{% endblock %}
{% block title_h1 %}Editar Categoría{% endblock %}

{% block content %}
<div class="container mx-auto p-6">
    <div class="max-w-lg mx-auto bg-white p-8 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold text-center text-gray-700 mb-6">Actualizar Categoría</h2>
        
        <form method="POST">
            <div class="mb-4">
                <label for="name" class="block text-lg font-medium text-gray-600">Nombre de la categoría</label>
                <input type="text" id="name" name="name" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" value="{{ category.name }}" required>
            </div>

            <div class="flex justify-between">
                <button type="submit" class="px-6 py-2 bg-yellow-600 text-white rounded-md hover:bg-yellow-700 focus:ring-2 focus:ring-yellow-400">Actualizar Categoría</button>
                <a href="{{ url_for('category.show') }}" class="px-6 py-2 bg-gray-300 text-gray-800 rounded-md hover:bg-gray-400 focus:ring-2 focus:ring-gray-400">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/category/show.html
{% extends "admin/layout.html" %}
{% block title %}Categorias{% endblock %}
{% block title_h1 %}Categorias{% endblock %}

{% block content %}
<div class="container mx-auto p-6">
    <div class="flex flex-col lg:flex-row justify-between mb-6 items-center">
        <!-- Botón para agregar nuevo producto -->
        <a href="{{ url_for('category.create') }}" class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-300 transition duration-200 w-full lg:w-auto mb-4 lg:mb-0 flex items-center justify-center space-x-2">
            <i class="fas fa-plus"></i>
            <span>Agregar Nueva Categoría</span>
        </a>

        <!-- Formulario de búsqueda -->
        <form method="get" action="{{ url_for('product.show') }}" class="flex items-center space-x-2 w-full lg:w-auto">
            <input type="text" name="search" value="{{ search }}" placeholder="Buscar producto..." class="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 transition duration-200 w-full lg:w-64">
            <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-4 focus:ring-blue-300 transition duration-200 w-24 lg:w-auto">
                Buscar
            </button>
        </form>
    </div>

    <!-- Tabla de categorías -->
    <div class="overflow-x-auto bg-white shadow-lg rounded-lg">
        <table class="min-w-full table-auto">
            <thead class="bg-gray-100 text-gray-700">
                <tr>
                    <th class="px-6 py-3 text-left">#</th>
                    <th class="px-6 py-3 text-left">Nombre</th>
                    <th class="px-6 py-3 text-left">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories.items %}
                    <tr class="border-t hover:bg-gray-50 transition duration-200">
                        <td class="px-6 py-3">{{ loop.index }}</td>
                        <td class="px-6 py-3">{{ category.name }}</td>
                        <td class="px-6 py-3 flex space-x-2">
                            <!-- Botón de edición con icono y color pastel -->
                            <a href="{{ url_for('category.edit', id=category.id) }}" 
                               class="px-2 py-1 bg-yellow-200 text-yellow-800 rounded-md hover:bg-yellow-300 focus:ring-2 focus:ring-yellow-100 transition duration-200">
                               <i class="fas fa-edit"></i>
                            </a>

                            <!-- Formulario para eliminar categoría con icono y color pastel -->
                            <form action="{{ url_for('category.delete', id=category.id) }}" method="post" style="display:inline;">
                                <button type="submit" class="px-2 py-1 bg-red-200 text-red-800 rounded-md hover:bg-red-300 focus:ring-2 focus:ring-red-100 transition duration-200">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Paginación -->
<div class="mt-6 flex justify-between items-center">
    <div class="pagination">
        {% if categories.has_prev %}
            <a href="{{ url_for('category.show', page=categories.prev_num, search=search) }}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 focus:ring-2 focus:ring-gray-200 transition duration-200">Anterior</a>
        {% endif %}
    </div>

    <span class="text-gray-600">Página {{ categories.page }} de {{ categories.pages }}</span>

    <div class="pagination">
        {% if categories.has_next %}
            <a href="{{ url_for('category.show', page=categories.next_num, search=search) }}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 focus:ring-2 focus:ring-gray-200 transition duration-200">Siguiente</a>
        {% endif %}
    </div>
</div>
{% endblock %}