app/models/product.py
from app import db
from datetime import datetime

class Product(db.Model):
    __tablename__ = 'products'

    id              = db.Column(db.Integer, primary_key=True)
    name            = db.Column(db.String(100), nullable=False, unique=True)
    description     = db.Column(db.Text, nullable=True)
    price           = db.Column(db.Float, nullable=False) # Precio de Venta
    availability    = db.Column(db.Boolean, nullable=False, default=True)
    image           = db.Column(db.String(255), nullable=True)
    created_at      = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at      = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relaciones
    brand_id        = db.Column(db.Integer, db.ForeignKey('brands.id'), nullable=False)
    brand           = db.relationship('Brand', backref=db.backref('products', lazy=True))
    categories      = db.relationship('Category', secondary='product_categories', backref=db.backref('products', lazy=True))

    def __repr__(self):
        return f'<Product id={self.id}, name={self.name}, sale_price={self.sale_price}>'

app/blueprints/product.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models import Product, Category, Brand
from app import db
import os
from werkzeug.utils import secure_filename


product = Blueprint('product', __name__)
UPLOAD_FOLDER = 'app/static/img/image'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}


#Formatos permitidos
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


# Ver lista de Productos
@product.route('/products', methods=['GET'])
def show():
    # Número de productos por página
    per_page = 10

    # Obtener el número de página desde la URL (por defecto será 1 si no se proporciona)
    page = request.args.get('page', 1, type=int)

    # Obtener el término de búsqueda desde la URL (si lo hay)
    search = request.args.get('search', '', type=str)

    # Consultar y ordenar productos por fecha de actualización
    query = Product.query.order_by(Product.updated_at.desc())

    # Aplicar filtro de búsqueda si se proporciona
    if search:
        query = query.filter(Product.name.ilike(f'%{search}%'))

    # Realizar la paginación
    products = query.paginate(page=page, per_page=per_page, error_out=False)

    return render_template('product/show.html', products=products, search=search)


# Crear un producto nuevo
@product.route('/products/new', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        name            = request.form['name']
        categories      = request.form.getlist('categories')
        picture         = request.files.get('picture')

        # Verificar si el nombre del producto ya existe
        existing_product = Product.query.filter_by(name=name).first()
        if existing_product:
            flash('Ya existe un producto con ese nombre. Por favor, elige otro.', 'danger')
            return redirect(url_for('product.create'))

        # Guardar la imagen si existe y es válida
        picture_filename = None
        if picture and allowed_file(picture.filename):
            picture_filename = secure_filename(picture.filename)
            picture.save(os.path.join(UPLOAD_FOLDER, picture_filename))

        # Crear el nuevo producto
        new_product = Product(
            name        = name,
            description = request.form['description'],
            price       = float(request.form['sale_price']),
            availability= 'availability' in request.form,
            brand_id    = int(request.form['brand']),
            image       = picture_filename
        )
        
        # Asociar las categorías al producto
        for category_id in categories:
            category = Category.query.get(category_id)
            new_product.categories.append(category)

        # Agregar el nuevo producto a la base de datos
        db.session.add(new_product)
        db.session.commit()

        flash('Producto agregado exitosamente', 'success')
        return redirect(url_for('product.show'))

    # Obtener Productos y categorías para llenar los selectores
    brands = Brand.query.all()
    categories = Category.query.all()

    return render_template('product/create.html', brands=brands, categories=categories)



# Editar una Producto
# Editar un Producto
@product.route('/products/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    product = Product.query.get_or_404(id)  # Buscar el producto por su ID
    if request.method == 'POST':
        name = request.form['name']
        categories = request.form.getlist('categories')
        picture = request.files.get('picture')

        # Verificar si el nombre del producto ya existe y no es el mismo que el producto actual
        existing_product = Product.query.filter_by(name=name).first()
        if existing_product and existing_product.id != product.id:
            flash('Ya existe un producto con ese nombre. Por favor, elige otro.', 'danger')
            return redirect(url_for('product.edit', id=product.id))

        # Actualizar los datos del producto
        product.name = name
        product.description = request.form['description']
        product.price = float(request.form['sale_price'])
        product.availability = 'availability' in request.form
        product.brand_id = int(request.form['brand'])

        # Si se sube una nueva imagen, guardar la nueva imagen
        if picture and allowed_file(picture.filename):
            # Eliminar la imagen anterior si existe
            if product.image:
                old_image_path = os.path.join(UPLOAD_FOLDER, product.image)
                if os.path.exists(old_image_path):
                    os.remove(old_image_path)  # Eliminar la imagen anterior

            picture_filename = secure_filename(picture.filename)
            picture.save(os.path.join(UPLOAD_FOLDER, picture_filename))
            product.image = picture_filename  # Actualizar la imagen del producto

        # Actualizar las categorías del producto
        product.categories.clear()  # Eliminar las categorías anteriores
        for category_id in categories:
            category = Category.query.get(category_id)
            product.categories.append(category)

        # Guardar los cambios en la base de datos
        db.session.commit()

        flash('Producto actualizado exitosamente', 'success')
        return redirect(url_for('product.show'))

    # Obtener marcas y categorías para llenar los selectores
    brands = Brand.query.all()
    categories = Category.query.all()

    return render_template('product/edit.html', product=product, brands=brands, categories=categories)



# Eliminar un Producto
@product.route('/products/delete/<int:id>', methods=['POST'])
def delete(id):
    # Obtener el producto por su ID
    product = Product.query.get_or_404(id)

    # Eliminar la imagen del producto si existe
    if product.image:
        image_path = os.path.join(UPLOAD_FOLDER, product.image)
        if os.path.exists(image_path):
            os.remove(image_path)  # Eliminar la imagen

    # Eliminar las asociaciones en la tabla intermedia 'product_categories' si es necesario
    for category in product.categories:
        product.categories.remove(category)

    # Eliminar el producto
    db.session.delete(product)
    db.session.commit()

    flash('Producto eliminado exitosamente', 'success')
    return redirect(url_for('product.show'))

app/templates/product/create.html
{% extends "admin/layout.html" %}

{% block title %}Nuevo Producto{% endblock %}
{% block title_h1 %}Agregar Nuevo Producto{% endblock %}

{% block content %}
<div class="container mx-auto p-2">
    <div class="max-w-lg mx-auto bg-white p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold text-center text-gray-700 mb-6">Agregar Nuevo Producto</h2>
        
        <!-- Barra de estado -->
        <div class="mb-6 flex justify-between">
            <div id="step1" class="step-icon cursor-pointer flex items-center gap-1" onclick="moveToSection(0)">
                <i class="fas fa-info-circle text-xl"></i>
                <span class="text-sm hidden sm:block">Información Básica</span> <!-- Solo visible en pantallas medianas en adelante -->
            </div>
            <div id="step2" class="step-icon cursor-pointer flex items-center gap-1" onclick="moveToSection(1)">
                <i class="fas fa-dollar-sign text-xl"></i>
                <span class="text-sm hidden sm:block">Precio</span> <!-- Solo visible en pantallas medianas en adelante -->
            </div>
            <div id="step3" class="step-icon cursor-pointer flex items-center gap-1" onclick="moveToSection(2)">
                <i class="fas fa-tag text-xl"></i>
                <span class="text-sm hidden sm:block">Marca y Categorías</span> <!-- Solo visible en pantallas medianas en adelante -->
            </div>
            <div id="step4" class="step-icon cursor-pointer flex items-center gap-1" onclick="moveToSection(3)">
                <i class="fas fa-image text-xl"></i>
                <span class="text-sm hidden sm:block">Imágen</span> <!-- Solo visible en pantallas medianas en adelante -->
            </div>
        </div>



        <form method="POST" enctype="multipart/form-data">
            <!-- Sección 1: Información Básica -->
            <div id="section1" class="form-section">
                <!-- Nombre del producto -->
                <div class="mb-4">
                    <label for="name" class="block text-lg font-medium text-gray-600">Nombre del Producto</label>
                    <input type="text" id="name" name="name" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" autocomplete="off" required>
                </div>

                <!-- Descripción del producto -->
                <div class="mb-4">
                    <label for="description" class="block text-lg font-medium text-gray-600">Descripción del Producto</label>
                    <textarea id="description" name="description" rows="3" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none"></textarea>
                </div>
                <!-- Disponibilidad -->
                <div class="mb-4">
                    <label for="availability" class="inline-flex items-center">
                        <input type="checkbox" id="availability" name="availability" class="form-checkbox" checked>
                        <span class="ml-2">Disponible</span>
                    </label>
                </div>
            </div>

            <!-- Sección 2: Precios del Producto -->
            <div id="section2" class="form-section hidden">
                <!-- Precio de venta -->
                <div class="mb-4">
                    <label for="sale_price" class="block text-lg font-medium text-gray-600">Precio de Venta</label>
                    <input type="number" id="sale_price" name="sale_price" step="0.01" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" required>
                </div>
            </div>

            <!-- Sección 3: Marca y Categorías -->
            <div id="section3" class="form-section hidden">
                <!-- Marca -->
                <div class="mb-4">
                    <label for="brand" class="block text-lg font-medium text-gray-600">Marca</label>
                    <select id="brand" name="brand" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" required>
                        {% for brand in brands %}
                            <option value="{{ brand.id }}">{{ brand.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Categorías -->
                <div class="mb-4">
                    <label for="categories" class="block text-lg font-medium text-gray-600">Categorías</label>
                    <select id="categories" name="categories" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" multiple>
                        {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <!-- Sección 4: Imágenes -->
            <div id="section4" class="form-section hidden">
                <!-- Imagen principal -->
                <div class="mb-4">
                    <label for="picture" class="block text-lg font-medium text-gray-600">Imagen del Producto</label>
                    <input type="file" id="picture" name="picture" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" required>
                </div>
            </div>

            <!-- Botones de navegación -->
            <div class="flex justify-between mt-4">
                <button type="button" id="prevBtn" class="px-6 py-2 bg-gray-300 text-gray-800 rounded-md hover:bg-gray-400 focus:ring-2 focus:ring-gray-400" onclick="move(-1)">Anterior</button>
                <button type="button" id="nextBtn" class="px-6 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:ring-2 focus:ring-green-400" onclick="move(1)">Siguiente</button>
            </div>
            
            <!-- Botón de enviar al final -->
            <div class="flex justify-end mt-4">
                <button type="submit" id="submitBtn" class="px-6 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:ring-2 focus:ring-green-400 hidden">Agregar Producto</button>
            </div>
        </form>
    </div>
</div>

<script src="{{ url_for('static', filename='js/currentSection.js') }}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var choices = new Choices('#categories', {
            removeItemButton: true,
            maxItemCount: 5,
            searchEnabled: false,
            itemSelectText: 'Presiona para seleccionar'
        });
    });
</script>
{% endblock %}

app/templates/product/edit.html
{% extends "admin/layout.html" %}

{% block title %}Editar Producto{% endblock %}
{% block title_h1 %}Actualizar Producto{% endblock %}

{% block content %}
<div class="container mx-auto p-2">
    <div class="max-w-lg mx-auto bg-white p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold text-center text-gray-700 mb-6">Actualizar Producto</h2>
        
        <!-- Barra de estado -->
        <div class="mb-6 flex justify-between">
            <div id="step1" class="step-icon cursor-pointer flex items-center gap-1" onclick="moveToSection(0)">
                <i class="fas fa-info-circle text-xl"></i>
                <span class="text-sm hidden sm:block">Información Básica</span> <!-- Solo visible en pantallas medianas en adelante -->
            </div>
            <div id="step2" class="step-icon cursor-pointer flex items-center gap-1" onclick="moveToSection(1)">
                <i class="fas fa-dollar-sign text-xl"></i>
                <span class="text-sm hidden sm:block">Precio</span> <!-- Solo visible en pantallas medianas en adelante -->
            </div>
            <div id="step3" class="step-icon cursor-pointer flex items-center gap-1" onclick="moveToSection(2)">
                <i class="fas fa-tag text-xl"></i>
                <span class="text-sm hidden sm:block">Marca y Categorías</span> <!-- Solo visible en pantallas medianas en adelante -->
            </div>
            <div id="step4" class="step-icon cursor-pointer flex items-center gap-1" onclick="moveToSection(3)">
                <i class="fas fa-image text-xl"></i>
                <span class="text-sm hidden sm:block">Imágen</span> <!-- Solo visible en pantallas medianas en adelante -->
            </div>
        </div>

        <form action="{{ url_for('product.edit', id=product.id) }}" method="POST" enctype="multipart/form-data">
            <div id="section1" class="form-section">
                <div class="mb-4">
                    <label for="name" class="block text-lg font-medium text-gray-600">Nombre del Producto</label>
                    <input type="text" id="name" name="name" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" value="{{ product.name }}" required>
                </div>
                <div class="mb-4">
                    <label for="description" class="block text-lg font-medium text-gray-600">Descripción del Producto</label>
                    <textarea id="description" name="description" rows="3" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none">{{ product.description }}</textarea>
                </div>
                <div class="mb-4">
                    <label for="availability" class="inline-flex items-center">
                        <input type="checkbox" id="availability" name="availability" class="form-checkbox" {% if product.availability %}checked{% endif %}>
                        <span class="ml-2">Disponible</span>
                    </label>
                </div>
            </div>

            <div id="section2" class="form-section hidden">
                <div class="mb-4">
                    <label for="sale_price" class="block text-lg font-medium text-gray-600">Precio de Venta</label>
                    <input type="number" id="sale_price" name="sale_price" step="0.01" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" value="{{ product.price }}" required>
                </div>
            </div>

            <div id="section3" class="form-section hidden">
                <div class="mb-4">
                    <label for="brand" class="block text-lg font-medium text-gray-600">Marca</label>
                    <select id="brand" name="brand" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" required>
                        {% for brand in brands %}
                            <option value="{{ brand.id }}" {% if brand.id == product.brand_id %}selected{% endif %}>{{ brand.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-4">
                    <label for="categories" class="block text-lg font-medium text-gray-600">Categorías</label>
                    <select id="categories" name="categories" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none" multiple>
                        {% for category in categories %}
                            <option value="{{ category.id }}" {% if category in product.categories %}selected{% endif %}>{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div id="section4" class="form-section hidden">
                {% if product.image %}
                    <img src="{{ url_for('static', filename='img/image/' + product.image) }}" alt="Imagen actual" class="w-32 mt-2">
                {% endif %}
                <div class="mb-4">
                    <label for="picture" class="block text-lg font-medium text-gray-600">Imagen Del Producto</label>
                    <input type="file" id="picture" name="picture" class="w-full mt-2 p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none">
                </div>
            </div>

            <!-- Botones de navegación -->
            <div class="flex justify-between mt-6">
                <button type="button" id="prevBtn" class="px-6 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 focus:ring-2 focus:ring-gray-400 hidden" onclick="move(-1)">Anterior</button>
                <button type="button" id="nextBtn" class="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:ring-2 focus:ring-blue-400" onclick="move(1)">Siguiente</button>
            </div>
            <!-- Botón de envío al final -->
            <button type="submit" id="submitBtn" class="px-6 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:ring-2 focus:ring-green-400 hidden">Actualizar Producto</button>
        </form>
    </div>
</div>

<script src="{{ url_for('static', filename='js/currentSection.js') }}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var choices = new Choices('#categories', {
            removeItemButton: true,
            maxItemCount: 5,
            searchEnabled: false,
            itemSelectText: 'Presiona para seleccionar'
        });
    });
</script>
{% endblock %}

app/templates/product/show.html
{% extends "admin/layout.html" %}

{% block title %}Productos{% endblock %}
{% block title_h1 %}Productos{% endblock %}

{% block content %}
<div class="container mx-auto p-6">
    <div class="flex flex-col lg:flex-row justify-between mb-6 items-center">
        <!-- Botón para agregar nuevo producto -->
        <a href="{{ url_for('product.create') }}" class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-300 transition duration-200 w-full lg:w-auto mb-4 lg:mb-0 flex items-center justify-center space-x-2">
            <i class="fas fa-plus"></i>
            <span>Agregar Nuevo Producto</span>
        </a>

        <!-- Formulario de búsqueda -->
        <form method="get" action="{{ url_for('product.show') }}" class="flex items-center space-x-2 w-full lg:w-auto">
            <input type="text" name="search" value="{{ search }}" placeholder="Buscar producto..." class="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 transition duration-200 w-full lg:w-64">
            <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-4 focus:ring-blue-300 transition duration-200 w-24 lg:w-auto">
                Buscar
            </button>
        </form>
    </div>

    <div class="overflow-x-auto bg-white shadow-md rounded-lg">
        <table class="min-w-full table-auto">
            <thead>
                <tr class="bg-gray-100 hidden lg:table-row">
                    <th class="py-2 px-4 text-left">#</th>
                    <th class="py-2 px-4 text-left">Nombre</th>
                    <th class="py-2 px-4 text-left whitespace-nowrap">Precio</th>
                    <th class="py-2 px-4 text-left">Disponibilidad</th>
                    <th class="py-2 px-4 text-left">Marca</th>
                    <th class="py-2 px-4 text-left">Categorías</th>
                    <th class="py-2 px-4 text-left">Imagen</th>
                    <th class="py-2 px-4 text-left">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products.items %}
                <tr class="border-t hover:bg-gray-50 transition duration-200 hidden lg:table-row">
                    <td class="py-2 px-4">{{ loop.index }}</td>
                    <td class="py-2 px-4 whitespace-nowrap overflow-hidden text-ellipsis max-w-xs">{{ product.name }}</td>
                    <td class="py-2 px-4">${{ product.price }}</td>
                    <td class="py-2 px-4">
                        {% if product.availability %}
                            <span class="text-green-500">Disponible</span>
                        {% else %}
                            <span class="text-red-500">No disponible</span>
                        {% endif %}
                    </td>
                    <td class="py-2 px-4">{{ product.brand.name }}</td>
                    <td class="py-2 px-4">
                        {% for category in product.categories %}
                            <span class="block">{{ category.name }}</span>
                        {% endfor %}
                    </td>
                    <td class="py-2 px-4">
                        {% if product.image %}
                            <img src="{{ url_for('static', filename='img/image/' + product.image) }}" alt="Imagen principal" class="max-w-full h-auto rounded-md mx-auto" width="100px">
                        {% endif %}
                    </td>
                    <td class="py-2 px-4 flex justify-center items-center space-x-2">
                        <a href="{{ url_for('product.edit', id=product.id) }}" class="px-2 py-1 bg-yellow-200 text-yellow-800 rounded-md hover:bg-yellow-300 focus:ring-2 focus:ring-yellow-100 transition duration-200">
                            <i class="fas fa-edit"></i>
                        </a>
                        <form action="{{ url_for('product.delete', id=product.id) }}" method="POST" class="inline">
                            <button type="submit" class="px-2 py-1 bg-red-200 text-red-800 rounded-md hover:bg-red-300 focus:ring-2 focus:ring-red-100 transition duration-200">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                    </td>
                </tr>

                <!-- Diseño para pantallas pequeñas -->
                <div class="lg:hidden mb-6 border border-gray-200 p-6 rounded-xl bg-white shadow-md">
                    <div class="text-2xl font-semibold text-gray-800 mb-2">{{ product.name }}</div>
                    <div class="text-lg text-gray-600 mb-2"><strong>Precio:</strong> ${{ product.price }}</div>
                    <div class="text-lg text-gray-600 mb-2">
                        <strong>Disponibilidad:</strong> 
                        {% if product.availability %}
                            <span class="text-green-500">Disponible</span>
                        {% else %}
                            <span class="text-red-500">No disponible</span>
                        {% endif %}
                    </div>
                    <div class="text-lg text-gray-600 mb-2"><strong>Marca:</strong> {{ product.brand.name }}</div>
                    <div class="text-lg text-gray-600 mb-4"><strong>Categorías:</strong>
                        {% for category in product.categories %}
                            <span class="block text-sm text-gray-500">{{ category.name }}</span>
                        {% endfor %}
                    </div>
                    <div class="mb-4">
                        <strong>Imagen:</strong>
                        {% if product.image %}
                            <img src="{{ url_for('static', filename='img/image/' + product.image) }}" alt="Imagen principal" class="max-w-full h-auto rounded-md mx-auto">
                        {% endif %}
                    </div>
                    <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4 justify-center">
                        <a href="{{ url_for('product.edit', id=product.id) }}" class="px-6 py-2 bg-yellow-400 text-white rounded-lg hover:bg-yellow-500 focus:ring-2 focus:ring-yellow-200 transition duration-200 w-full sm:w-auto text-center">
                            <i class="fas fa-edit"></i> Editar
                        </a>
                        <form action="{{ url_for('product.delete', id=product.id) }}" method="POST" class="inline w-full sm:w-auto">
                            <button type="submit" class="px-6 py-2 bg-red-400 text-white rounded-lg hover:bg-red-500 focus:ring-2 focus:ring-red-200 transition duration-200 w-full sm:w-auto text-center">
                                <i class="fas fa-trash-alt"></i> Eliminar
                            </button>
                        </form>
                    </div>
                </div>
                {% endfor %}
            </tbody>
        </table>

    </div>

    <div class="mt-6 flex justify-between items-center">
        <div class="pagination">
            {% if products.has_prev %}
                <a href="{{ url_for('product.show', page=products.prev_num, search=search) }}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 focus:ring-2 focus:ring-gray-200 transition duration-200">Anterior</a>
            {% endif %}
        </div>

        <span class="text-gray-600">Página {{ products.page }} de {{ products.pages }}</span>

        <div class="pagination">
            {% if products.has_next %}
                <a href="{{ url_for('product.show', page=products.next_num, search=search) }}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 focus:ring-2 focus:ring-gray-200 transition duration-200">Siguiente</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}